name: Test All Packages

on: push

jobs:
  test:
    name: Node.js and Browser (Chrome) Tests
    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node (10)
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: yarn build
      run: yarn build
